name: Dockerize web app
on: push
jobs:
  build-container:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ssp25/ssp-nodejs-proj
          tags: latest, ${{ github.run_number }}